[package]
name = "meq"
version = "0.1.0"
edition = "2021"

[lib]
name = "meq"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.17.3"
features = ["extension-module", "abi3-py37"]

[dependencies]
